# Generated by Django 6.0.6 on 2026-07-05 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_en', models.CharField(db_index=True, max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_code', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'db_table': 'branches',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('sector_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sector_name', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sectors',
            },
        ),
        migrations.CreateModel(
            name='BranchStructure',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='organization.branch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='organization.department')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='organization.sector')),
            ],
            options={
                'verbose_name': 'Branch Structure',
                'verbose_name_plural': 'Branch Structures',
                'db_table': 'branch_structure',
                'unique_together': {('branch', 'sector', 'department')},
            },
        ),
    ]
