# Generated by Django 6.0.6 on 2026-07-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchstructure',
            name='id',
            field=models.BigAutoField(db_column='structure_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sector',
            name='sector_name',
            field=models.CharField(db_column='name', db_index=True, max_length=255),
        ),
    ]
