# Generated by Django 6.0.6 on 2026-07-05 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_branchstructure_id_alter_sector_sector_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='updated_at',
        ),
    ]
