# Generated by Django 6.0.6 on 2026-07-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_remove_sector_created_at_remove_sector_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.BigAutoField(db_column='dept_id', primary_key=True, serialize=False),
        ),
    ]
