# Generated by Django 6.0.6 on 2026-07-06 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_department_id'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='department',
        #     name='created_at',
        # ),
        # migrations.RemoveField(
        #     model_name='department',
        #     name='updated_at',
        # ),
    ]
