# Generated by Django 6.0.6 on 2026-08-13 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_remove_department_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='name_en',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='name_en',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SubDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_departments', to='organization.branchstructure')),
            ],
            options={
                'verbose_name': 'Sub Department',
                'verbose_name_plural': 'Sub Departments',
                'db_table': 'sub_departments',
                'unique_together': {('branch_structure', 'name')},
            },
        ),
    ]
