# Generated by Django 6.0.6 on 2026-08-13 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_department_name_en_sector_name_en_subdepartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='name_en',
        ),
    ]
