# Generated by Django 6.0.6 on 2026-07-05 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hardware_specs', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Employee Code')),
                ('name_ar', models.CharField(max_length=255, verbose_name='Name (Arabic)')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (English)')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch_structure', models.ForeignKey(blank=True, db_column='branch_structure_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organization.branchstructure', verbose_name='Branch Structure')),
            ],
            options={
                'db_table': 'custody_employee',
            },
        ),
        migrations.CreateModel(
            name='ConsumerCustody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('issue', 'صرف عهدة'), ('return', 'إرجاع للمخزن')], max_length=10)),
                ('assignment_date', models.DateField(verbose_name='Assignment Date')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Return Date')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_history', to='hardware_specs.baseasset')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='custodies', to='custody.employee')),
            ],
            options={
                'db_table': 'custody_consumercustody',
            },
        ),
    ]
