# Generated by Django 6.0.6 on 2026-07-06 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0001_initial'),
        ('organization', '0005_remove_department_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumercustody',
            name='branch_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='structure_custodies', to='organization.branchstructure', verbose_name='Assigned to Branch/Sector/Department'),
        ),
        migrations.AlterField(
            model_name='consumercustody',
            name='employee',
            field=models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custodies', to='custody.employee'),
        ),
    ]
