# Generated by Django 6.0.6 on 2026-07-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0003_alter_consumercustody_assigned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumercustody',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='السبب / Reason'),
        ),
        migrations.AlterField(
            model_name='consumercustody',
            name='action_type',
            field=models.CharField(choices=[('issue', 'صرف عهدة'), ('return', 'إرجاع للمخزن'), ('destructed', 'تكهين / إتلاف'), ('maintenance', 'صيانة'), ('upgrade', 'ترقية / تحديث'), ('layoff', 'إيقاف مؤقت / إنهاء الخدمة'), ('retired', 'تقاعد العهدة')], max_length=15),
        ),
    ]
