# Generated by Django 6.0.6 on 2026-07-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0004_consumercustody_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'نشط / Active'), ('retired', 'متقاعد / Retired'), ('layedoff', 'إنهاء الخدمة / Laid Off')], default='active', max_length=15, verbose_name='Status'),
        ),
    ]
