# Generated by Django 6.0.6 on 2026-07-05 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hardware_specs', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, verbose_name='Item Name (e.g., HP 963X Ink / Backpack Bag)')),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('part_number', models.CharField(blank=True, max_length=150, null=True)),
                ('quantity_in_stock', models.PositiveIntegerField(default=0, verbose_name='Available Quantity in Stock')),
                ('minimum_required_qty', models.PositiveIntegerField(default=5, verbose_name='Minimum Limit for Low Stock Alerts')),
                ('unit', models.CharField(choices=[('pcs', 'Piece (حبة/قطعة)'), ('box', 'Box (علبة/صندوق)'), ('meter', 'Meter (متر)'), ('pack', 'Pack (عبوة)')], default='pcs', max_length=20, verbose_name='Unit of Measurement')),
                ('storage_location', models.CharField(blank=True, max_length=150, null=True, verbose_name='Storage Rack / Location')),
                ('compatible_with_model', models.CharField(blank=True, max_length=255, null=True, verbose_name='Compatible with Hardware Models')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Notes / Specifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='hardware_specs.assetcategory')),
                ('stored_in_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stock_items', to='organization.branch')),
            ],
            options={
                'verbose_name': 'Inventory Accessory',
                'verbose_name_plural': 'Inventory Accessories',
                'db_table': 'inventory_accessories_stock',
                'unique_together': {('part_number', 'stored_in_branch', 'item_name')},
            },
        ),
        migrations.CreateModel(
            name='InventoryTransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('addition', 'New Item Registered (إضافة صنف جديد)'), ('increase', 'Stock Increase / Inbound (زيادة رصيد)'), ('decrease', 'Stock Decrease / Outbound (صرف رصيد)'), ('delete', 'Record Deleted (حذف صنف)')], max_length=20)),
                ('item_type', models.CharField(choices=[('accessory', 'Accessory / Consumable'), ('hardware', 'Hardware Asset')], max_length=20)),
                ('quantity_changed', models.IntegerField(default=0, verbose_name='Quantity Delta (+/-)')),
                ('new_total_quantity', models.PositiveIntegerField(default=0, verbose_name='Resulting Stock Balance')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Reason / Transaction Details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hardware_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs', to='hardware_specs.baseasset')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='inventory.inventoryitem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_transaction_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
