# Generated by Django 6.0.6 on 2026-07-05 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, unique=True, verbose_name='Category Name (EN) e.g., Computer, Printer, Handheld')),
                ('name_ar', models.CharField(max_length=100, unique=True, verbose_name='اسم التصنيف (بالعربي) مثل: حواسب، طابعات')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رمز اختياري للتصنيف (e.g., PC, PRN)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category_type', models.CharField(choices=[('accessory', 'Accessory (Cables, Mice, Keyboard, etc.)'), ('base_asset', 'Base Asset (Computers, Monitors, Printers, etc.)'), ('spare_parts', 'Spare Parts (Replacement Components, etc.)')], default='base_asset', max_length=20, verbose_name='Category Type')),
            ],
            options={
                'verbose_name': 'Asset Category',
                'verbose_name_plural': 'Asset Categories',
                'db_table': 'asset_categories',
            },
        ),
        migrations.CreateModel(
            name='BaseAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_stock', 'In Inventory / Stock (بالمخزن وغير معين لمستهلك)'), ('assigned', 'Assigned to Consumer (صُرف كعهدة لموظف أو موقع)'), ('maintenance', 'In Maintenance (في الصيانة)'), ('scrapped', 'Scrapped / Disposed (مكهن)')], default='in_stock', max_length=20)),
                ('brand', models.CharField(db_index=True, max_length=100)),
                ('model_or_pn', models.CharField(blank=True, max_length=150, null=True, verbose_name='Model / Part No.')),
                ('serial_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='hardware_specs.assetcategory')),
            ],
            options={
                'db_table': 'hardware_assets',
            },
        ),
        migrations.CreateModel(
            name='ComputerAsset',
            fields=[
                ('baseasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hardware_specs.baseasset')),
                ('pc_type', models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop')], default='laptop', max_length=10)),
                ('processor', models.CharField(blank=True, max_length=150, null=True)),
                ('memory_ram', models.CharField(blank=True, max_length=50, null=True)),
                ('hard_disk', models.CharField(blank=True, max_length=100, null=True)),
                ('monitor_brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Attached Monitor Brand')),
                ('monitor_model', models.CharField(blank=True, max_length=150, null=True, verbose_name='Attached Monitor Model/PN')),
                ('monitor_inches', models.CharField(blank=True, max_length=50, null=True, verbose_name='Attached Monitor Size (Inches)')),
                ('monitor_serial', models.CharField(blank=True, max_length=150, null=True, verbose_name='Attached Monitor S/N')),
                ('keyboard_brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Keyboard Brand')),
                ('keyboard_model', models.CharField(blank=True, max_length=150, null=True, verbose_name='Keyboard Model/PN')),
                ('keyboard_serial', models.CharField(blank=True, max_length=150, null=True, verbose_name='Keyboard S/N')),
                ('mouse_brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mouse Brand')),
                ('mouse_model', models.CharField(blank=True, max_length=150, null=True, verbose_name='Mouse Model/PN')),
                ('mouse_serial', models.CharField(blank=True, max_length=150, null=True, verbose_name='Mouse S/N')),
                ('bag_brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bag Brand')),
                ('bag_model_or_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bag Model / Description')),
            ],
            options={
                'db_table': 'asset_computers',
            },
            bases=('hardware_specs.baseasset',),
        ),
        migrations.CreateModel(
            name='MonitorAsset',
            fields=[
                ('baseasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hardware_specs.baseasset')),
                ('part_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='Part No.')),
                ('inches', models.CharField(max_length=50, verbose_name='Screen Size (Inches)')),
                ('location_details', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location (الموقع داخل الفرع)')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color')),
                ('is_meeting_room_tv', models.BooleanField(default=False, verbose_name='Is Greater than 70 inch / Meeting Room TV')),
                ('is_curved', models.BooleanField(default=False, verbose_name='Is Curved Screen')),
            ],
            options={
                'verbose_name': 'Monitor / TV Asset',
                'verbose_name_plural': 'Monitor / TV Assets',
                'db_table': 'asset_monitors',
            },
            bases=('hardware_specs.baseasset',),
        ),
        migrations.CreateModel(
            name='NetworkDeviceAsset',
            fields=[
                ('baseasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hardware_specs.baseasset')),
                ('device_type', models.CharField(max_length=100, verbose_name='Switch / Router / AP')),
                ('ports_count', models.IntegerField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asset_network_devices',
            },
            bases=('hardware_specs.baseasset',),
        ),
        migrations.CreateModel(
            name='PrinterAsset',
            fields=[
                ('baseasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hardware_specs.baseasset')),
                ('multifunctions', models.CharField(blank=True, max_length=100, null=True, verbose_name='Multifunctions (e.g., All In One)')),
                ('printer_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Printer Type (e.g., Color/Mono)')),
                ('printer_color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Printer Body Color')),
                ('connection_type', models.CharField(blank=True, max_length=150, null=True, verbose_name='Supported Connections (e.g., Ethernet-WiFi-USB)')),
                ('technology', models.CharField(blank=True, max_length=100, null=True, verbose_name='Technology (e.g., Inkjet/Laser)')),
                ('cartridge_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cartridge Number (e.g., HP 963X)')),
                ('cartridge_color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cartridge Color Type')),
                ('ink_details', models.TextField(blank=True, null=True, verbose_name='Ink Details (e.g., 4 ink_Black/Cyan...)')),
                ('active_connection', models.CharField(blank=True, max_length=50, null=True, verbose_name='Active Connection (e.g., USB/Ethernet)')),
                ('mac_address_eth', models.CharField(blank=True, max_length=50, null=True, verbose_name='MAC Address (Ethernet)')),
                ('ip_address_eth', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address (Ethernet)')),
                ('mac_address_wifi', models.CharField(blank=True, max_length=50, null=True, verbose_name='MAC Address (WiFi)')),
            ],
            options={
                'verbose_name': 'Printer Asset',
                'verbose_name_plural': 'Printer Assets',
                'db_table': 'asset_printers',
            },
            bases=('hardware_specs.baseasset',),
        ),
        migrations.CreateModel(
            name='TabletAsset',
            fields=[
                ('baseasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hardware_specs.baseasset')),
                ('device_item_type', models.CharField(max_length=50, verbose_name='Item Type (e.g., Tablet/Ipad)')),
                ('storage_ram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Storage & RAM Specs')),
                ('screen_color_specs', models.CharField(blank=True, max_length=150, null=True, verbose_name='Color & Screen Specs')),
            ],
            options={
                'verbose_name': 'Tablet / iPad Asset',
                'verbose_name_plural': 'Tablet / iPad Assets',
                'db_table': 'asset_tablets',
            },
            bases=('hardware_specs.baseasset',),
        ),
        migrations.AddIndex(
            model_name='baseasset',
            index=models.Index(fields=['status', 'category'], name='hardware_as_status_71eb26_idx'),
        ),
    ]
