# Generated by Django 6.0.6 on 2026-09-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_specs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printerasset',
            name='multifunctions',
            field=models.BooleanField(default=False, verbose_name='Multifunctions (e.g., All In One)'),
        ),
    ]
